// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSMS.Infrastructure.Data;

#nullable disable

namespace VSMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VsmsDbContext))]
    [Migration("20260128203701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSMS.Core.Entities.ActionToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ShiftId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("VolunteerId");

                    b.ToTable("ActionTokens");
                });

            modelBuilder.Entity("VSMS.Core.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("VSMS.Core.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VolunteerId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("VSMS.Core.Entities.MasterScheduleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultVolunteerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultVolunteerId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("DayOfWeek", "TimeSlotId", "Role")
                        .IsUnique();

                    b.ToTable("MasterScheduleEntries");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MonthPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReminderSentAt24Hours")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderSentAt7Days")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("Date", "TimeSlotId", "Role")
                        .IsUnique();

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("VSMS.Core.Entities.ShiftRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResolvedByAdminId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByAdminId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftId", "VolunteerId", "Status");

                    b.ToTable("ShiftRequests");
                });

            modelBuilder.Entity("VSMS.Core.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Morning",
                            SortOrder = 1,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Afternoon",
                            SortOrder = 2,
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Evening",
                            SortOrder = 3,
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Saturday Morning",
                            SortOrder = 4,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Saturday Afternoon",
                            SortOrder = 5,
                            StartTime = new TimeOnly(13, 0, 0)
                        });
                });

            modelBuilder.Entity("VSMS.Core.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBackup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("VSMS.Core.Entities.ActionToken", b =>
                {
                    b.HasOne("VSMS.Core.Entities.Shift", "Shift")
                        .WithMany("ActionTokens")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany("ActionTokens")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("VSMS.Core.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.MasterScheduleEntry", b =>
                {
                    b.HasOne("VSMS.Core.Entities.Volunteer", "DefaultVolunteer")
                        .WithMany("DefaultScheduleEntries")
                        .HasForeignKey("DefaultVolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("MasterScheduleEntries")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultVolunteer");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Shift", b =>
                {
                    b.HasOne("VSMS.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Shifts")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany("Shifts")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TimeSlot");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.ShiftRequest", b =>
                {
                    b.HasOne("VSMS.Core.Entities.AdminUser", "ResolvedByAdmin")
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Shift", "Shift")
                        .WithMany("ShiftRequests")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany("ShiftRequests")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedByAdmin");

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Shift", b =>
                {
                    b.Navigation("ActionTokens");

                    b.Navigation("ShiftRequests");
                });

            modelBuilder.Entity("VSMS.Core.Entities.TimeSlot", b =>
                {
                    b.Navigation("MasterScheduleEntries");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Volunteer", b =>
                {
                    b.Navigation("ActionTokens");

                    b.Navigation("DefaultScheduleEntries");

                    b.Navigation("ShiftRequests");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
