// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSMS.Infrastructure.Data;

#nullable disable

namespace VSMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VsmsDbContext))]
    [Migration("20260202082119_AddRequestedSlotToShiftRequest")]
    partial class AddRequestedSlotToShiftRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("VSMS.Core.Entities.ActionToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ShiftId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("VolunteerId");

                    b.ToTable("ActionTokens");
                });

            modelBuilder.Entity("VSMS.Core.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("VSMS.Core.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VolunteerId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Backup1VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Backup2VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderSentAt24Hours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReminderSentAt7Days")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Backup1VolunteerId");

                    b.HasIndex("Backup2VolunteerId");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("Date", "TimeSlotId")
                        .IsUnique();

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("VSMS.Core.Entities.ShiftRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedSlot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByAdminId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftId", "VolunteerId", "Status");

                    b.ToTable("ShiftRequests");
                });

            modelBuilder.Entity("VSMS.Core.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Morning",
                            SortOrder = 1,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Afternoon",
                            SortOrder = 2,
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Evening",
                            SortOrder = 3,
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Saturday Morning",
                            SortOrder = 4,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 180,
                            IsActive = true,
                            Label = "Saturday Afternoon",
                            SortOrder = 5,
                            StartTime = new TimeOnly(13, 0, 0)
                        });
                });

            modelBuilder.Entity("VSMS.Core.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("VSMS.Core.Entities.ActionToken", b =>
                {
                    b.HasOne("VSMS.Core.Entities.Shift", "Shift")
                        .WithMany("ActionTokens")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany("ActionTokens")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("VSMS.Core.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Shift", b =>
                {
                    b.HasOne("VSMS.Core.Entities.Volunteer", "Backup1Volunteer")
                        .WithMany()
                        .HasForeignKey("Backup1VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Backup2Volunteer")
                        .WithMany()
                        .HasForeignKey("Backup2VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Shifts")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany("Shifts")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Backup1Volunteer");

                    b.Navigation("Backup2Volunteer");

                    b.Navigation("TimeSlot");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.ShiftRequest", b =>
                {
                    b.HasOne("VSMS.Core.Entities.AdminUser", "ResolvedByAdmin")
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VSMS.Core.Entities.Shift", "Shift")
                        .WithMany("ShiftRequests")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSMS.Core.Entities.Volunteer", "Volunteer")
                        .WithMany("ShiftRequests")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedByAdmin");

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Shift", b =>
                {
                    b.Navigation("ActionTokens");

                    b.Navigation("ShiftRequests");
                });

            modelBuilder.Entity("VSMS.Core.Entities.TimeSlot", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("VSMS.Core.Entities.Volunteer", b =>
                {
                    b.Navigation("ActionTokens");

                    b.Navigation("ShiftRequests");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
