// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolunteerCoordinator.Infrastructure.Persistence;

#nullable disable

namespace VolunteerCoordinator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VolunteerCoordinatorDbContext))]
    [Migration("20260921093943_PolicyAndRecurringCommitments")]
    partial class PolicyAndRecurringCommitments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolunteerCoordinator.Domain.Access.RecoveryToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSlotId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VolunteerId", "ShiftSlotId", "ExpiresAtUtc");

                    b.ToTable("RecoveryTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecoveryTokens_TokenHash", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Access.VolunteerAccessCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IssuedReason")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftSlotId", "VolunteerId")
                        .IsUnique()
                        .HasDatabaseName("UX_VolunteerAccessCapabilities_ActiveCommitment")
                        .HasFilter("\"InvalidatedAtUtc\" IS NULL");

                    b.ToTable("VolunteerAccessCapabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_VolunteerAccessCapabilities_TokenHash", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.ActionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AssignmentId", "Action")
                        .IsUnique()
                        .HasDatabaseName("UX_ActionTokens_UnusedAssignmentAction")
                        .HasFilter("\"UsedAtUtc\" IS NULL");

                    b.ToTable("ActionTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActionTokens_TokenHash", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedByCoordinatorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSlotId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_ActiveSlot")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("SourceRequestId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftId", "VolunteerId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_ActiveVolunteerShift")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveLocalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndLocalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleKind")
                        .HasColumnType("integer");

                    b.Property<int>("RolePosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePolicy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("WithdrawalEffectiveLocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("WithdrawnAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.HasIndex("SourceRequestId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("State", "EndLocalDate")
                        .HasDatabaseName("IX_RecurringCommitments_State_End");

                    b.HasIndex("SeriesId", "RoleKind", "RolePosition", "EffectiveLocalDate", "EndLocalDate")
                        .HasDatabaseName("IX_RecurringCommitments_Overlap");

                    b.ToTable("RecurringCommitments", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringCommitments_Range", "\"EndLocalDate\" >= \"EffectiveLocalDate\"");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VolunteerId", "CommitmentId")
                        .HasDatabaseName("IX_RecurringCommitmentCapabilities_Volunteer_Commitment");

                    b.ToTable("RecurringCommitmentCapabilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringCommitmentCapabilities_TokenHash", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RecurringOccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_RecurringCommitmentOccurrences_Assignment")
                        .HasFilter("\"AssignmentId\" IS NOT NULL");

                    b.HasIndex("CommitmentId", "RecurringOccurrenceId")
                        .IsUnique();

                    b.HasIndex("RecurringOccurrenceId", "State")
                        .HasDatabaseName("IX_RecurringCommitmentOccurrences_Occurrence_State");

                    b.ToTable("RecurringCommitmentOccurrences", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveLocalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndLocalDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("RecurringCommitmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByCoordinatorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleKind")
                        .HasColumnType("integer");

                    b.Property<int>("RolePosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePolicy")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecurringCommitmentId");

                    b.HasIndex("RevisionId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("SeriesId", "VolunteerId", "RoleKind", "RolePosition", "EffectiveLocalDate", "EndLocalDate")
                        .IsUnique()
                        .HasDatabaseName("UX_RecurringCommitmentRequests_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("RecurringCommitmentRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringCommitmentRequests_Range", "\"EndLocalDate\" >= \"EffectiveLocalDate\"");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.NotificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransitionId", "State");

                    b.ToTable("NotificationAttempts", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.NotificationDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NotificationIntentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("NotificationIntentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("NotificationDeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.NotificationIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClaimOwnerToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastProviderEventAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RecoveryTokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique()
                        .HasFilter("\"State\" IN (0, 1, 2)");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                    b.HasIndex("RecoveryTokenId");

                    b.HasIndex("ShiftSlotId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("State", "NextAttemptAtUtc", "CreatedAtUtc");

                    b.ToTable("NotificationIntents", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.ResendWebhookReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ProviderOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SvixId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderMessageId");

                    b.HasIndex("SvixId")
                        .IsUnique();

                    b.ToTable("ResendWebhookReceipts", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Requests.ShiftRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByCoordinatorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftSlotId", "VolunteerId")
                        .IsUnique()
                        .HasDatabaseName("UX_ShiftRequests_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("ShiftRequests", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.RecurringShiftOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsException")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("ResolutionActor")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("ResolutionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedLocalStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.HasIndex("ShiftId")
                        .IsUnique()
                        .HasDatabaseName("UX_RecurringShiftOccurrences_Shift")
                        .HasFilter("\"ShiftId\" IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RecurringShiftOccurrences_Status");

                    b.HasIndex("SeriesId", "LocalDate")
                        .IsUnique();

                    b.ToTable("RecurringShiftOccurrences", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringShiftOccurrences_State", "(\"Status\" = 0 AND \"ShiftId\" IS NOT NULL) OR (\"Status\" IN (1, 2) AND \"ShiftId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRevisionNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastGeneratedThroughLocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "UpdatedAtUtc")
                        .HasDatabaseName("IX_RecurringShiftSeries_Active");

                    b.ToTable("RecurringShiftSeries", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeriesRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmbiguousTimeChoice")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("AnchorLocalDate")
                        .HasColumnType("date");

                    b.Property<int>("BackupSlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByCoordinator")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EffectiveLocalDate")
                        .HasColumnType("date");

                    b.Property<int>("HorizonWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("InternalCoordinatorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("LocalStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RecurrenceKind")
                        .HasColumnType("integer");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SignupPolicy")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("VolunteerInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("WeeklyDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "EffectiveLocalDate")
                        .IsUnique();

                    b.HasIndex("SeriesId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("RecurringShiftSeriesRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringShiftSeriesRevisions_BackupSlots", "\"BackupSlotCount\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_RecurringShiftSeriesRevisions_Duration", "\"DurationMinutes\" BETWEEN 1 AND 10080");

                            t.HasCheckConstraint("CK_RecurringShiftSeriesRevisions_Horizon", "\"HorizonWeeks\" BETWEEN 4 AND 26");

                            t.HasCheckConstraint("CK_RecurringShiftSeriesRevisions_Interval", "\"Interval\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecurringOccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SignupPolicy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VolunteerInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RecurringOccurrenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Shifts_RecurringOccurrence")
                        .HasFilter("\"RecurringOccurrenceId\" IS NOT NULL");

                    b.HasIndex("IsActive", "PublishedAtUtc", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("IX_Shifts_PublicOpening");

                    b.ToTable("Shifts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_Interval", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.ShiftSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId", "Kind", "Position")
                        .IsUnique();

                    b.ToTable("ShiftSlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftSlots_Position", "(\"Kind\" = 0 AND \"Position\" = 1) OR (\"Kind\" = 1 AND \"Position\" BETWEEN 1 AND 2)");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Settings.GroupSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("GroupSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_GroupSettings_Singleton", "\"Id\" = '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Volunteers.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnonymizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnonymizedAtUtc")
                        .HasDatabaseName("IX_Volunteers_AnonymizedAtUtc");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Access.RecoveryToken", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Access.VolunteerAccessCapability", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.ActionToken", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Assignments.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Requests.ShiftRequest", null)
                        .WithMany()
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitment", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeriesRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentRequest", null)
                        .WithMany()
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentCapability", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Commitments.RecurringCommitment", null)
                        .WithMany()
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentOccurrence", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Assignments.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolunteerCoordinator.Domain.Commitments.RecurringCommitment", null)
                        .WithMany()
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftOccurrence", null)
                        .WithMany()
                        .HasForeignKey("RecurringOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Commitments.RecurringCommitmentRequest", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Commitments.RecurringCommitment", null)
                        .WithMany()
                        .HasForeignKey("RecurringCommitmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeriesRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.NotificationDeliveryAttempt", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Notifications.NotificationIntent", null)
                        .WithMany()
                        .HasForeignKey("NotificationIntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.NotificationIntent", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Access.RecoveryToken", null)
                        .WithMany()
                        .HasForeignKey("RecoveryTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Requests.ShiftRequest", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.RecurringShiftOccurrence", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeriesRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeriesRevision", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.Shift", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.RecurringShiftOccurrence", null)
                        .WithOne()
                        .HasForeignKey("VolunteerCoordinator.Domain.Schedules.Shift", "RecurringOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.ShiftSlot", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.Shift", null)
                        .WithMany("Slots")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.Shift", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
