// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolunteerCoordinator.Infrastructure.Persistence;

#nullable disable

namespace VolunteerCoordinator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VolunteerCoordinatorDbContext))]
    partial class VolunteerCoordinatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.ActionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AssignmentId", "Action")
                        .IsUnique()
                        .HasDatabaseName("UX_ActionTokens_UnusedAssignmentAction")
                        .HasFilter("\"UsedAtUtc\" IS NULL");

                    b.ToTable("ActionTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActionTokens_TokenHash", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedByCoordinatorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSlotId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_ActiveSlot")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("SourceRequestId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftId", "VolunteerId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_ActiveVolunteerShift")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Notifications.NotificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransitionId", "State");

                    b.ToTable("NotificationAttempts", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Requests.ShiftRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByCoordinatorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ShiftSlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StatusTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("StatusTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatusTokenHash")
                        .IsUnique();

                    b.HasIndex("VolunteerId");

                    b.HasIndex("ShiftSlotId", "VolunteerId")
                        .IsUnique()
                        .HasDatabaseName("UX_ShiftRequests_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("ShiftRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftRequests_StatusTokenHash", "octet_length(\"StatusTokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "PublishedAtUtc", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("IX_Shifts_PublicOpening");

                    b.ToTable("Shifts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Shifts_Interval", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.ShiftSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId", "Kind", "Position")
                        .IsUnique();

                    b.ToTable("ShiftSlots", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftSlots_Position", "(\"Kind\" = 0 AND \"Position\" = 1) OR (\"Kind\" = 1 AND \"Position\" BETWEEN 1 AND 2)");
                        });
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Volunteers.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.ActionToken", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Assignments.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Requests.ShiftRequest", null)
                        .WithMany()
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Requests.ShiftRequest", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.ShiftSlot", null)
                        .WithMany()
                        .HasForeignKey("ShiftSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerCoordinator.Domain.Volunteers.Volunteer", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.ShiftSlot", b =>
                {
                    b.HasOne("VolunteerCoordinator.Domain.Schedules.Shift", null)
                        .WithMany("Slots")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerCoordinator.Domain.Schedules.Shift", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
